FROM ros:humble-ros-base

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    git \
    vim \
    python3-pip \
    python3-colcon-common-extensions \
    ros-humble-rclcpp \
    ros-humble-rclcpp-components \
    ros-humble-geometry-msgs \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspaces/code

COPY basic_ws/src ./src

RUN /bin/bash -c "source /opt/ros/${ROS_DISTRO}/setup.bash && \
    colcon build --symlink-install"

CMD ["/bin/bash"]
