FROM ros:humble-ros-base

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    git \
    vim \
    python3-pip \
    ros-humble-rclcpp \
    ros-humble-rclcpp-components \
    ros-humble-geometry-msgs \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspaces/code
